language: go

go:
    - 1.7

install:
    - go get
    - go get -u github.com/nats-io/gnatsd
    - go get -u github.com/stretchr/testify
    - go get golang.org/x/tools/cmd/cover
    - go get github.com/mattn/goveralls

script:
    - go test -v -covermode=count -coverprofile=coverage.out
    - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci -repotoken 9GPJSocOIVZBeNNIRQNLJxNU2lJfKiAtY
